### ISSUE TITLE
Create Routing Component and Update app.tsx to Include Routing Component

### ISSUE THREAD

**Issue by MVDem** [MVDem/market-client#3]
#### Description:
We need to update the app.tsx file to include the newly created Routing component. This will integrate client-side routing into our application, allowing navigation between different pages.

#### Tasks:
1. **Update app.tsx:**
   -  Open the app.tsx file in the project.
   -  Import the Routing component at the top of the file.
   -  Replace the existing routing setup (if any) with the <Routing /> component.

2. **Create Routing Component:**
   -  Create a new function component named Routing.
   -  Import necessary dependencies: BrowserRouter, Suspense, Routes, Route, Navigate.
   -  Set up the routing structure as described below:
      ```jsx
      function Routing() {
        return (
          <BrowserRouter>
            <Suspense fallback="Loading...">
              <Routes>
                <Route path="*" element={<Navigate to="/" />} />
                ...
                </Route>
              </Routes>
            </Suspense>
          </BrowserRouter>
        );
      }
      export default Routing;
      ```

#### Acceptance Criteria:
- [x] app.tsx file updated to include the Routing component.
- [x] The application successfully renders with client-side routing enabled.
- [ ] Navigation between different pages works correctly.
- [x] Routing component created with the specified structure.
- [ ] Routes defined for different pages in the application.
- [ ] Private routes implemented and properly protected.
- [x] Component tested and confirmed to work as expected.

#### Additional Notes:
- Ensure that the app.tsx file is updated in the correct location within the project structure.
- Verify that the Routing component is properly integrated and functioning as expected.
