### ISSUE TITLE
Create default empty pages (HomePage, SignPage, Layout) and integrate them into Routes.tsx

### ISSUE THREAD

**Issue by MVDem** [MVDem/market-client#5]
**Description:**

Create three default empty pages: `HomePage`, `SignPage`, and `Layout`. Each page should return an `h1` header with the respective page name. Integrate these pages into the `routes/Routes.tsx` file and verify that they work correctly.

## Tasks:

- **Create Pages:**
    - [x] Create a `HomePage` component that returns an `h1` header with the text "Home Page".
    - [x] Create a `SignPage` component that returns an `h1` header with the text "Sign Page".
    - [x] Create a `Layout` component that returns an `h1` header with the text "Layout".

- **Integrate into Routes:**
    - [x] Update the `routes/Routes.tsx` file to include routes for `HomePage`, `SignPage`, and `Layout`.

- **Verify Functionality:**
    - [x] Ensure that navigating to the respective routes displays the correct `h1` header.

## Steps to Reproduce:

1. **Create the `HomePage` component in the `pages` directory:**
    ```jsx
    // src/pages/HomePage/HomePage.tsx
    import React from 'react';

    const HomePage = () => {
        return <h1>Home Page</h1>;
    };

    export default HomePage;
    ```

2. **Create the `SignPage` component in the `pages` directory:**
    ```jsx
    // src/pages/SignPage/SignPage.tsx
    import React from 'react';

    const SignPage = () => {
        return <h1>Sign Page</h1>;
    };

    export default SignPage;
    ```

3. **Create the `Layout` component in the `pages` directory:**
    ```jsx
    // src/pages/Layout/Layout.tsx
    import React from 'react';

    const Layout = () => {
        return <h1>Layout</h1>;
    };

    export default Layout;
    ```

4. **Update the `routes/Routes.tsx` file to include the new pages:**
    ```jsx
    // src/routes/Routes.tsx
    import HomePage from '../pages/HomePage';
    import SignPage from '../pages/SignPage';
    import Layout from '../pages/Layout';

    const Routes = () => {
        return (
            <Router>
             ...
            </Router>
        );
    };

    export default Routes;
    ```

5. **Test the setup by running the application and navigating to the routes:**
    - `/` should display "Home Page".
    - `/sign` should display "Sign Page".
    - `/layout` should display "Layout".

**Expected Result:**

Each route should display the correct `h1` header, indicating that the page components are set up and integrated correctly.
